name: bezier
version: 1.2.0
description: >-
  A 2D BÃ©zier curve math library. Based heavily on the work of @TheRealPomax
  <pomax.github.io/bezierjs>.

  Live examples can be found at <www.dartographer.com/bezier>.
homepage: https://github.com/aab29/bezier.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  vector_math: ^2.1.0
dev_dependencies:
  test: ^1.16.8
