name: bezier
version: 1.0.3
authors:
  - Aaron Barrett <aaron@aaronbarrett.com>
  - Isaac Barrett <ikebart9999@gmail.com>
description: >-
  A 2D BÃ©zier curve math library. Based heavily on the work of @TheRealPomax
  <pomax.github.io/bezierjs>.

  Live examples can be found at <www.dartographer.com/bezier>.
homepage: https://github.com/aab29/bezier.dart
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  vector_math: ^2.0.0
dev_dependencies:
  test: ^1.0.0
